// Arabic Labels
export const labels = {
  addNewProperty: "إضافة عقار جديد",
  editProperty: "تعديل العقار",
  propertyTitle: "عنوان العقار",
  description: "وصف العقار",
  descriptionPlaceholder: `اكتب وصفاً تفصيلياً للعقار...

- موقع العقار وأهم المعالم القريبة
- تفاصيل التشطيب والديكور
- المميزات الخاصة (مثل: شرفة، حديقة، موقف سيارات)
- المرافق المتوفرة (مثل: مسبح، صالة رياضية، حراسة)
- حالة العقار وسنة البناء
- تفاصيل إضافية مهمة للمشتري/المستأجر`,
  descriptionHelp: "اكتب وصفاً شاملاً يساعد المشتري/المستأجر في فهم مميزات العقار",
  price: "السعر",
  currency: "ريال سعودي",
  propertyType: "نوع العقار",
  propertyStatus: "حالة العقار",
  bedrooms: "غرف النوم",
  bathrooms: "الحمامات",
  area: "المساحة (متر مربع)",
  location: "الموقع/المنطقة",
  address: "العنوان",
  city: "المدينة",
  country: "الدولة",
  yearBuilt: "سنة البناء",
  parkingSpaces: "مواقف السيارات",
  features: "المميزات",
  amenities: "المرافق",
  propertyImages: "صور العقار",
  furnished: "مفروش",
  petFriendly: "يسمح بالحيوانات الأليفة",
  featured: "مميز",
  contactInfo: "معلومات الاتصال",
  contactInfoPlaceholder: "أدخل معلومات الاتصال (رقم الهاتف، البريد الإلكتروني، إلخ)",
  createProperty: "إنشاء العقار",
  updateProperty: "تحديث العقار",
  resetForm: "إعادة تعيين النموذج",
  saving: "جاري الحفظ...",
  totalProperties: "إجمالي العقارات",
  available: "متاح",
  APARTMENT: "شقة",
  VILLA: "فيلا",
  TOWNHOUSE: "تاون هاوس",
  PENTHOUSE: "بنتهاوس",
  STUDIO: "استوديو",
  OFFICE: "مكتب",
  SHOP: "محل تجاري",
  WAREHOUSE: "مستودع",
  LAND: "أرض",
  BUILDING: "مبنى",
  propertyCreatedSuccess: "تم إنشاء العقار بنجاح",
  propertyUpdatedSuccess: "تم تحديث العقار بنجاح",
  errorCreatingProperty: "حدث خطأ أثناء إنشاء العقار",
  errorUpdatingProperty: "حدث خطأ أثناء تحديث العقار",
  errorFetchingProperty: "حدث خطأ أثناء جلب بيانات العقار",
  featuresPlaceholder: "اضغط Enter لإضافة ميزة جديدة",
  amenitiesPlaceholder: "اضغط Enter لإضافة مرفق جديد",
  dragDropImages: "اسحب وأسقط الصور هنا، أو انقر للاختيار",
  dropImagesHere: "اسقط الصور هنا...",
  removeImage: "إزالة الصورة",
  uploadMoreImages: "تحميل المزيد من الصور",
  imagePreview: "معاينة الصور",
  noImagesSelected: "لم يتم اختيار أي صور بعد.",
  formResetSuccess: "تم إعادة تعيين النموذج.",
  autoSaved: "تم حفظ البيانات تلقائياً",
  furnishedDescription: "العقار يأتي مع الأثاث",
  petFriendlyDescription: "يُسمح بالحيوانات الأليفة",
  featuredDescription: "إبراز هذا العقار",
  enterToAddNew: "اكتب واضغط Enter للإضافة...",
  selectPropertyType: "اختر نوع العقار",
  selectPropertyStatus: "اختر حالة العقار",
  addressPlaceholder: "عنوان الشارع...",
  cityPlaceholder: "الرياض، جدة، الدمام...",
  locationPlaceholder: "وسط المدينة، حي الملك فهد، الكورنيش...",
  maxFilesInfo: "(%s صور كحد أقصى)",
}; 